path=./build/classes/
class=$(path)javarmi/
all:
	@make -s run

#build:
#	@javac $(class)Virus.java $(class)Graph.java $(class)Vertex.java

run:
	@java -classpath $(path) javarmi.JavaRMI

#test:
#	@make -s build
#	@java -classpath $(path) virus.Virus test

#clean:
	@rm -rf $(path)*.class
